FROM pytorch/pytorch
WORKDIR /app
# RUN apt-get update  && rm -rf /var/lib/apt/lists/*
# COPY requirements.txt requirements.txt
# RUN pip install -U pip
# RUN pip install -r requirements.txt
# COPY . .
# RUN rm -r /app/api/uploads/*; exit 0
# RUN rm -r /app/api/static/*; exit 0